#!/usr/bin/env node

/**
 * @file sync_python_wasm_runtime.ts
 * @description Generate or verify the Python WASM embedded runtime from the package runtime source.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const SOURCE_PATH = path.join(ROOT, 'python_runtime', 'src', 'deckrogue_rules_core', 'runtime.py');
const TARGET_PATH = path.join(ROOT, 'src', 'content', 'narrative', 'pythonRuntime.ts');

function normalizePathForComment(filePath: string): string {
  return path.relative(ROOT, filePath).replace(/\\/g, '/');
}

function buildGeneratedModule(runtimeSource: string): string {
  return `/**
 * @file pythonRuntime.ts
 * @description Generated Python runtime string for the browser Pyodide lane.
 *
 * Source: ${normalizePathForComment(SOURCE_PATH)}
 * Regenerate: npm run sync:python-wasm-runtime
 */

// @generated by scripts/validation/sync_python_wasm_runtime.ts
export const PYTHON_RUNTIME_CODE = ${JSON.stringify(runtimeSource)};\n`;
}

function normalizeRuntimeSource(runtimeSource: string): string {
  return runtimeSource.replace(/\r\n?/g, '\n');
}

function assertRuntimeSourceLooksComplete(runtimeSource: string): void {
  const requiredSnippets = [
    'class RuleRuntime',
    'SECONDARY_RESOURCES',
    'def init_runtime',
    'def dispatch_command',
    'def create_save_game_v2',
    'def restore_snapshot_from_save_game',
  ];
  const missing = requiredSnippets.filter((snippet) => !runtimeSource.includes(snippet));
  if (missing.length > 0) {
    throw new Error(`Python runtime source is missing required snippet(s): ${missing.join(', ')}`);
  }
}

function main(): void {
  const checkOnly = process.argv.includes('--check');
  if (!existsSync(SOURCE_PATH)) {
    throw new Error(`Missing Python runtime source: ${SOURCE_PATH}`);
  }

  const runtimeSource = normalizeRuntimeSource(readFileSync(SOURCE_PATH, 'utf-8'));
  assertRuntimeSourceLooksComplete(runtimeSource);
  const generated = buildGeneratedModule(runtimeSource);

  if (checkOnly) {
    const current = existsSync(TARGET_PATH)
      ? normalizeRuntimeSource(readFileSync(TARGET_PATH, 'utf-8'))
      : '';
    if (current !== generated) {
      console.error('[sync_python_wasm_runtime] Embedded runtime is out of sync.');
      console.error(`  Source: ${normalizePathForComment(SOURCE_PATH)}`);
      console.error(`  Target: ${normalizePathForComment(TARGET_PATH)}`);
      console.error('  Run: npm run sync:python-wasm-runtime');
      process.exit(1);
    }
    console.log('[sync_python_wasm_runtime] OK');
    return;
  }

  writeFileSync(TARGET_PATH, generated);
  console.log(`[sync_python_wasm_runtime] wrote ${normalizePathForComment(TARGET_PATH)}`);
}

main();
