export {
  type AnimationSpeed,
  type AnimationQuality,
  type AmbientProfile,
  type MotionConfig,
  type MotionTokens,
  type ToastType,
  type ToastMessage,
  type SceneId,
  type SceneTransition,
  MOTION_TOKENS,
  QUALITY_CONFIGS,
  COMBAT_BEATS,
  getMotionConfig,
  setAnimationSpeed,
  setAnimationQuality,
  setAmbientProfile,
  getMotionTokens,
  getQualityConfig,
  applyMotionConfigToDOM,
  showToast,
  dismissToast,
  dismissAllToasts,
  getToasts,
  subscribeToToasts,
  emitSceneTransition,
  triggerCombatBeat,
  triggerScreenShake,
  getAmbientClassForScene,
  prefersReducedMotion,
  shouldReduceAnimations,
  initMotionConfig,
} from './motionSystem';

export { ToastContainer } from './ToastContainer';
export { SceneTransitionWrapper, AmbientLayer, SceneContainer } from './SceneTransition';
